name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    # For some reason github.
    - name: Output Project Name
      id: project_name
      run: |
        export NAME="${GITHUB_REPOSITORY#*/}"
        echo "name=${NAME}" >> $GITHUB_OUTPUT
    - name: Display Project Name
      run: |
        echo "Building Project '${{ steps.project_name.outputs.name }}'"
    - uses: leafo/gh-actions-lua@v9
      with:
        buildCache: false
    - uses: leafo/gh-actions-luarocks@v4
    - name: Install Lua Packages
      run: |
        luarocks make --dev
    - name: Test Project
      run: moon build.moon src -t
    - name: Compile Project
      run: moon build.moon src -d -y
    # Build the applications
    - uses: nhartland/love-build@master
      with:
       app_name: ${{ steps.project_name.outputs.name }}
       love_version: '11.4'
    # Upload the built applications
    - uses: actions/upload-artifact@v3
      with:
        name: built-applications
        path: 'release'
